server:
  port: 1100
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eacdy/spring-cloud-pom/     # 配置git url
          search-paths: config-repo                             # git url 下的相對位置，可以配置多個，用,分割。
          username:                                             # git username
          password:                                             # git password